version: '3'
volumes:
  volume_app_filestore:
  volume_app_project:
  volume_db:
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - volume_app_filestore:/var/lib/odoo/
      - volume_app_project:/mnt/extra-addons/
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - volume_db:/var/lib/postgresql/
      
